# Generated by Django 3.2.10 on 2024-09-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='Register',
        ),
    ]
