# Generated by Django 3.2.10 on 2024-09-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20240910_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('measure', models.CharField(max_length=50)),
            ],
        ),
    ]
