# Generated by Django 3.2.10 on 2024-09-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_additem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
