# Generated by Django 3.2.10 on 2024-09-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
